name: Sync Crowdin
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0
        with:
          persist-credentials: false
      - name: Crowdin Sync
        id: crowdin-download
        uses: crowdin/github-action@08713f00a50548bfe39b37e8f44afb53e7a802d4 # 2.12.0
        with:
          config: crowdin.yml
          upload_sources: true
          download_translations: true
          localization_branch_name: l10n_crowdin_translations
          create_pull_request: true
          pull_request_base_branch_name: main
          pull_request_title: 'chore(i18n): new crowdin translations'
          pull_request_body: 'New translations from [SoulFireClient Crowdin](https://crowdin.com/project/soulfireclient)'
          pull_request_labels: crowdin
          commit_message: 'chore(i18n): updated translations from crowdin'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Enable auto-merge for the PR
        if: steps.crowdin-download.outputs.pull_request_url
        run: gh pr --repo $GITHUB_REPOSITORY merge ${STEPS_CROWDIN_DOWNLOAD_OUTPUTS_PULL_REQUEST_URL} --auto --merge
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          STEPS_CROWDIN_DOWNLOAD_OUTPUTS_PULL_REQUEST_URL: ${{ steps.crowdin-download.outputs.pull_request_url }}